[package]
name = "bincrypt"
version = "0.2.0"
authors = ["frk <hazefrk+dev@gmail.com>"]

[dependencies]
base64 = "0.9.0"
failure = "0.1.1"
rust_sodium = "0.7.0"
structopt = "0.1.6"
structopt-derive = "0.1.6"
