comment_width = 100
imports_layout = "HorizontalVertical"
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
unstable_features = true
use_try_shorthand = true
wrap_comments = true
write_mode = "overwrite"
